# Generated by Django 4.2.5 on 2024-08-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Categories',
        ),
    ]
