# Generated by Django 5.1 on 2024-09-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
